var djela = [
	"Napiši pozitivnu poruku i ostavi je na automobilu nepoznate osobe.",
	"Pomozi roditeljima u kućanskim poslovima.",
	"Posadi drvo ili biljku.",
	"Jedan dan misli samo pozitivno.",
	"Jedan se dan suzdrži od prigovaranja.",
	"Pitaj barem 2 drage osobe kako su provele dan.",
	"Napiši pismo starijoj osobi i ubaci joj u sandučić.",
	"Nahrani ptičice u parku.",
	"Operi odjeću koju više ne koristiš i pokloni ju.",
	"Oprosti nekome tko te povrijedio i na koga si se ljutio.",
	"Ubaci anonimno 'Želim ti super dan.' u susjedov poštanski sandučić.",
	"Iznenadi nekoga od ukućana tako da mu pospremiš sobu.",
	"Izdvoji jedan dan i posveti ga samo svojoj obitelji.",
	"Pokloni osmijeh prolazniku.",
	"Pokloni kompliment trima osobama.",
	"Ostavi na prozoru mrvice kruha za ptičice.",
	"Nacrtaj svojim bližnjima crtež koji prikazuje koliko ih voliš.",
	"Pročitaj knjigu po preporuci prijatelja iz razreda.",
	"Zapiši lijepe misli i pokloni ih dragoj osobi.",
	"Pitaj svoje bližnje kako su i porazgovaraj s njima.",
	"Pokušaj pomoći nekome kome je pomoć potrebna.",
	"Ostavi lijepu poruku na susjedovom kućnom pragu.",
	"Potakni dragu osobu na volontiranje.",
	"Potakni bližnje na druženje u prirodi.",
	"Izradi sliku s dragim ljudima i pokloni im.",
	"Pozovi u šetnju najboljeg prijatelja.",
	"Doniraj igračke domu za nezbrinutu djecu.",
	"Daruj obrok beskućniku.",
	"Napiši motivirajuće poruke i pokloni ih dragoj osobi.",
	"Nazovi nekoga s kime se nisi dugo čuo/čula.",
	"Pozovi prijatelje na društvenu igru na otvorenom.",
	"Zahvali dragoj osobi što je u tvom životu.",
	"Nahrani labudove na Maksimiru ili Jarunu.",
	"Nahrani psa lutalicu.",
	"Organiziraj filmsku večer za obitelj.",
	"Izradi božićnu čestitku svom prijatelju.",
	"Napiši nekome 'hvala ti na...' i daj mu tu poruku.",
	"Pošalji nekome čestitku za Novu godinu.",
	"Iznenadi nekog s njegovim omiljenim obrokom.",
	"Ostavi cvijet starijoj susjedi pred vratima.",
	"Nazovi prijatelja kojeg nisi dugo čuo/čula i pitaj ga kako je.",
	"Ostavi poštaru poruku 'Hvala :)' uz neku čokoladicu.",
	"Pokupi smeće s poda u prirodi i ubaci ga u koš za smeće.",
	"Nasmiješi se i pozdravi stranca.",
	"Pošalji karticu sa željama ozdravljenja nekome tko je bolestan.",
	"Odi u trgovinu susjedima koji su u izolaciji.",
	"Pitaj drage osobe kako su provele dan.",
	"Napiši pismo starijoj osobi u domu.",
	"Napiši i pošalji pismo dragoj osobi.",
	"Ispričaj vic i nasmij nekoga svaki dan praznika.",
	"Nacrtaj nešto i pokloni dragoj osobi.",
	"Učini nešto lijepo za prijatelja iz razreda s kojim se inače ne družiš.",
	"Pomozi svojim ukućanima.",
	"Stavi papirić s lijepom porukom u knjigu iz knjižnice.",
	"Zagrli svoje prijatelje barem 3 puta svaki dan praznika.",
	"Provedi poslijepodne s dragom osobom po njenoj želji.",
	"Danas pozorno slušaj što ti drugi govore.",
	"Danas govori samo lijepe riječi i pohvale.",
	"Danas provedi vrijeme samo sa svojim ukućanima.",
	"Danas izvrši sve zadatke na vrijeme.",
	"Nazovi člana obitelji s kojim se nisi dugo čuo.",
	"Ispeci kolač i podijeli ga sa susjedima.",
	"Pomozi starijoj osobi prijeći cestu.",
	"Popričaj s nekim iz razreda s kim se baš i ne družiš.",
	"Reci nekome da ga voliš.",
	"Tjedan dana pridrži vrata svakoj osobi koja ulazi/izlazi iz zgrade.",
	"Pripremi sam jedan obrok u danu.",
	"Provjeri kako su tvoji susjedi.",
	"Donesi doručak svojim roditeljima u krevet.",
	"Napravi sendvič i odnesi ga beskućniku.",
	"Napiši ohrabrujući citat i pošalji ga svom doktoru.",
	"Pomozi nekome kome je potrebna pomoć.",
	"Danas uputi osmijeh svakoj osobi koju sretneš.",
	"Ostavi poštaru poruku zahvale uz neku čokoladicu.",
	"Učini si ovaj dan za pamćenje.",
	"Napiši pjesmu za dragu osobu i pokloni joj.",
	"Pozovi sramežljivu osobu iz razreda u šetnju.",
	"Napiši pismo strancu i ostavi ga na klupici u parku.",
	"Ispeci kolače sa dragom osobom.",
	"Nahrani mačku na ulici.",
	"Iznenadi nekoga doručkom u krevetu.",
	"Isključi mobitel na jedan i uključi druženje s bližnjima.",
	"Napiši pismo svakom članu obitelji.",
	"Ostavi susjedu lijepu poruku ispred vrata.",
	"Pomozi prijatelju s učenjem.",
	"Očisti obližnji park s prijateljima.",
	"Stavi lijepu poruku susjedima u poštanski sandučić.",
	"Razgovaraj s osobom koja je usamljena.",
	"Organiziraj šetnju u prirodi s obitelji.",
	"Doniraj staru odjeću.",
]


function NovoDjelo() {
	var randomNumber = Math.floor(Math.random() * (djela.length));
	document.getElementById("DobraDjela").innerHTML = djela[randomNumber];
}